### ISSUE TITLE
无法发现小度音箱

### ISSUE THREAD

**Issue by yulechow** [dscao/dlna_dmr_xiaodu#1]
请问要发现小度音箱，是不是还要做什么操作？
![image](https://github.com/dscao/dlna_dmr_xiaodu/assets/98584009/5096efa7-47fe-48c6-a0c4-fe4961424190)

**Comment by dscao** [comment]
基于官方集成dlna dmr 修改的，如果官方的找不到，这个同样找不到。
另外现在的小度音箱很多版本都没有dlna功能了，请自行确认小度音箱是支持dlna的版本。

如果确认小度音箱是支持dlna的，只不过网络原因导致无法自动发现。可以不选择直接提交，后面就会出现让你手动填写设备描述 XML 文件网址，这样可以直接跨网段的使用。这个小度音箱的xml网址一般是 http://小度音箱IP:49494/description.xml
